### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission() and no delay is needed after a Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [wdq/SensorSeed#1]
In the file "SensorSeed/hardware/avr/outside/outside.ino", the Wire.requestFrom() is followed by a Wire.endTransmission() three times. You can remove those Wire.endTransmission(), since it is should only be used when writing data.

In the function getRain() the Wire.requestFrom() is followed by a `delay(50);`. You can remove that delay, since there is no need to wait after a Wire.requestFrom().

**Comment by wdq** [comment]
Thanks for pointing this out, I've updated the code.
